package com.qf58.learnwordapp;

import java.util.ArrayList;

/**
 * Created by linSir
 * date at 2017/12/4.
 * describe:
 */

public class Constant {

    private static ArrayList<Word> list = new ArrayList<>();

    public static void setAllList() {

        list.add(new Word(0, "dusty", "a", "多灰尘的", "垃圾箱", "尘土", "在"));
        list.add(new Word(1, "dustbin", "n", "垃圾箱 ", "多灰尘的", "垃圾箱", "尘土"));
        list.add(new Word(2, "dust", "n", "尘土", "垃圾箱 ", "多灰尘的", "垃圾箱"));
        list.add(new Word(3, "during", "prep", "在", "尘土", "垃圾箱 ", "多灰尘的"));
        list.add(new Word(4, "dumpling", "n", "一种食品(用肉和蔬菜作馅", "在", "尘土", "垃圾箱 "));
        list.add(new Word(5, "dull", "a", "迟钝的", "一种食品(用肉和蔬菜作馅", "在", "尘土"));
        list.add(new Word(6, "duke", "n", "公爵", "迟钝的", "一种食品(用肉和蔬菜作馅", "在"));
        list.add(new Word(7, "due", "a", "应支付的", "公爵", "迟钝的", "一种食品(用肉和蔬菜作馅"));
        list.add(new Word(8, "duck", "n", "鸭", "应支付的", "公爵", "迟钝的"));
        list.add(new Word(9, "ducat", "*n", "过去曾在欧洲的许多国家通用的金币名 ", "鸭", "应支付的", "公爵"));
        list.add(new Word(10, "dry", "a", "干(旱)的", "过去曾在欧洲的许多国家通用的金币名 ", "鸭", "应支付的"));
        list.add(new Word(11, "drunk", "a", "醉酒的", "干(旱)的", "过去曾在欧洲的许多国家通用的金币名 ", "鸭"));
        list.add(new Word(12, "drum", "n", "鼓", "醉酒的", "干(旱)的", "过去曾在欧洲的许多国家通用的金币名 "));
        list.add(new Word(13, "drug", "v", "掺麻醉药/毒药于(食物、饮料等);用药麻醉 ", "鼓", "醉酒的", "干(旱)的"));
        list.add(new Word(14, "drown", "v", "淹死", "掺麻醉药/毒药于(食物、饮料等);用药麻醉 ", "鼓", "醉酒的"));
        list.add(new Word(15, "drop", "v", "投下", "淹死", "掺麻醉药/毒药于(食物、饮料等);用药麻醉 ", "鼓"));
        list.add(new Word(16, "driver", "n", "司机", "投下", "淹死", "掺麻醉药/毒药于(食物、饮料等);用药麻醉 "));
        list.add(new Word(17, "drive", "v", "驾驶", "司机", "投下", "淹死"));
        list.add(new Word(18, "drink", "v", "(drank,drunk)喝", "驾驶", "司机", "投下"));
        list.add(new Word(19, "drill", "n", "钻头", "(drank,drunk)喝", "驾驶", "司机"));
        list.add(new Word(20, "drier", "*n", "吹风机 ", "钻头", "(drank,drunk)喝", "驾驶"));
        list.add(new Word(21, "dress", "n", "服装", "吹风机 ", "钻头", "(drank,drunk)喝"));
        list.add(new Word(22, "dream", "n", "梦(想)", "服装", "吹风机 ", "钻头"));
        list.add(new Word(23, "drawing", "n", "图画", "梦(想)", "服装", "吹风机 "));
        list.add(new Word(24, "drawer", "n", "拖曳者 ", "图画", "梦(想)", "服装"));
        list.add(new Word(25, "draw", "v", "画", "拖曳者 ", "图画", "梦(想)"));
        list.add(new Word(26, "drag", "n", "拖", "画", "拖曳者 ", "图画"));
        list.add(new Word(27, "dozen", "n", "一打", "拖", "画", "拖曳者 "));
        list.add(new Word(28, "downward", "a", "向下的", "一打", "拖", "画"));
        list.add(new Word(29, "downtown", "a", "在商业区的", "向下的", "一打", "拖"));
        list.add(new Word(30, "downstairs", "ad", "在楼下", "在商业区的", "向下的", "一打"));
        list.add(new Word(31, "downhill", "a", "&ad", "在楼下", "在商业区的", "向下的"));
        list.add(new Word(32, "down", "ad", "下", "&ad", "在楼下", "在商业区的"));
        list.add(new Word(33, "doubt", "n", "怀疑", "下", "&ad", "在楼下"));
        list.add(new Word(34, "double", "a", "两倍的", "怀疑", "下", "&ad"));
        list.add(new Word(35, "dot", "n", "小点", "两倍的", "怀疑", "下"));
        list.add(new Word(36, "door", "n", "门", "小点", "两倍的", "怀疑"));
        list.add(new Word(37, "dollar", "n", "美元", "门", "小点", "两倍的"));
        list.add(new Word(38, "dog", "n", "狗", "美元", "门", "小点"));
        list.add(new Word(39, "doctor", "n", "医生", "狗", "美元", "门"));
        list.add(new Word(40, "do", "aux", "v", "医生", "狗", "美元"));
        list.add(new Word(41, "division", "n", "分", "v", "医生", "狗"));
        list.add(new Word(42, "divide", "vt", "分", "分", "v", "医生"));
        list.add(new Word(43, "dive", "n", "跳水", "分", "分", "v"));
        list.add(new Word(44, "disturb", "vt", "打扰", "跳水", "分", "分"));
        list.add(new Word(45, "district", "n", "区", "打扰", "跳水", "分"));
        list.add(new Word(46, "distant", "a", "far away in space or time; not clear ", "区", "打扰", "跳水"));
        list.add(new Word(47, "distance", "n", "距离", "far away in space or time; not clear ", "区", "打扰"));
        list.add(new Word(48, "disobey", "v", "不服从", "距离", "far away in space or time; not clear ", "区"));
        list.add(new Word(49, "dislike", "vt", "consider unpleasant; not like ", "不服从", "距离", "far away in space or time; not clear "));
        list.add(new Word(50, "disk", "n", "圆盘", "consider unpleasant; not like ", "不服从", "距离"));
        list.add(new Word(51, "dish", "n", "碟", "圆盘", "consider unpleasant; not like ", "不服从"));
        list.add(new Word(52, "disease", "n", "病", "碟", "圆盘", "consider unpleasant; not like "));
        list.add(new Word(53, "discussion", "n", "讨论", "病", "碟", "圆盘"));
        list.add(new Word(54, "discuss", "vt", "讨论", "讨论", "病", "碟"));
        list.add(new Word(55, "discrimination", "n", "辩别力", "讨论", "讨论", "病"));
        list.add(new Word(56, "discovery", "n", "被发现的事物", "辩别力", "讨论", "讨论"));
        list.add(new Word(57, "discover", "vt", "发现", "被发现的事物", "辩别力", "讨论"));
        list.add(new Word(58, "discouraged", "a", "泄气的", "发现", "被发现的事物", "辩别力"));
        list.add(new Word(59, "disaster", "n", "灾难", "泄气的", "发现", "被发现的事物"));
        list.add(new Word(60, "disappointment", "n", "失望", "灾难", "泄气的", "发现"));
        list.add(new Word(61, "disappointing", "*a", "令人失望的", "失望", "灾难", "泄气的"));
        list.add(new Word(62, "disappointed", "a", "失望的", "令人失望的", "失望", "灾难"));
        list.add(new Word(63, "disappoint", "vt", "失望", "失望的", "令人失望的", "失望"));
        list.add(new Word(64, "disappear", "vi", "消失", "失望", "失望的", "令人失望的"));
        list.add(new Word(65, "disagreement", "n", "意见不一", "消失", "失望", "失望的"));
        list.add(new Word(66, "disagree", "v", "(with)意见不合", "意见不一", "消失", "失望"));
        list.add(new Word(67, "disadvantage", "n", "不利", "(with)意见不合", "意见不一", "消失"));
        list.add(new Word(68, "disabled", "a", "伤残的", "不利", "(with)意见不合", "意见不一"));
        list.add(new Word(69, "disability", "n", "机能丧失的状态", "伤残的", "不利", "(with)意见不合"));
        list.add(new Word(70, "dirty", "a", "肮脏的", "机能丧失的状态", "伤残的", "不利"));
        list.add(new Word(71, "dirt", "n", "污秽物(如灰尘", "肮脏的", "机能丧失的状态", "伤残的"));
        list.add(new Word(72, "directory", "n", "人名地址录", "污秽物(如灰尘", "肮脏的", "机能丧失的状态"));
        list.add(new Word(73, "director", "n", "导演", "人名地址录", "污秽物(如灰尘", "肮脏的"));
        list.add(new Word(74, "directly", "ad", "直接地", "导演", "人名地址录", "污秽物(如灰尘"));
        list.add(new Word(75, "direction", "n", "方向", "直接地", "导演", "人名地址录"));
        list.add(new Word(76, "direct", "a", "/ad", "方向", "直接地", "导演"));
        list.add(new Word(77, "dip", "v", "使", "/ad", "方向", "直接地"));
        list.add(new Word(78, "dinner", "n", "(一天中的)主餐", "使", "/ad", "方向"));
        list.add(new Word(79, "dining-room", "n", "餐室", "(一天中的)主餐", "使", "/ad"));
        list.add(new Word(80, "dingo", "*n", "澳洲的一种野狗 ", "餐室", "(一天中的)主餐", "使"));
        list.add(new Word(81, "digest", "vt", "消化", "澳洲的一种野狗 ", "餐室", "(一天中的)主餐"));
        list.add(new Word(82, "dig", "vt", "/vi", "消化", "澳洲的一种野狗 ", "餐室"));
        list.add(new Word(83, "difficulty", "n", "困难", "/vi", "消化", "澳洲的一种野狗 "));
        list.add(new Word(84, "difficult", "a", "困难的", "困难", "/vi", "消化"));
        list.add(new Word(85, "different", "a", "有差异的", "困难的", "困难", "/vi"));
        list.add(new Word(86, "difference", "n", "差别", "有差异的", "困难的", "困难"));
        list.add(new Word(87, "diet", "n", "日常饮食", "差别", "有差异的", "困难的"));
        list.add(new Word(88, "die", "vi", "死", "日常饮食", "差别", "有差异的"));
        list.add(new Word(89, "dictionary", "n", "辞典", "死", "日常饮食", "差别"));
        list.add(new Word(90, "dictation", "n", "口授笔录", "辞典", "死", "日常饮食"));
        list.add(new Word(91, "diary", "n", "日记", "口授笔录", "辞典", "死"));
        list.add(new Word(92, "diamond", "n", "钻石", "日记", "口授笔录", "辞典"));
        list.add(new Word(93, "dialogue", "n", "对话", "钻石", "日记", "口授笔录"));
        list.add(new Word(94, "dial", "n", "(钟表等的)针盘", "对话", "钻石", "日记"));
        list.add(new Word(95, "devotion", "n", "loyalty 献身", "(钟表等的)针盘", "对话", "钻石"));
        list.add(new Word(96, "devote", "vt", "将…奉献(给)", "loyalty 献身", "(钟表等的)针盘", "对话"));
        list.add(new Word(97, "development", "n", "发展", "将…奉献(给)", "loyalty 献身", "(钟表等的)针盘"));
        list.add(new Word(98, "develop", "vt", "发展", "发展", "将…奉献(给)", "loyalty 献身"));
        list.add(new Word(99, "determine", "vt", "确定", "发展", "发展", "将…奉献(给)"));
        list.add(new Word(100, "determination", "n", "决心", "确定", "发展", "发展"));
        list.add(new Word(101, "detective", "a", "侦察(用)的 n", "决心", "确定", "发展"));
        list.add(new Word(102, "destroy", "vt", "破坏", "侦察(用)的 n", "决心", "确定"));
        list.add(new Word(103, "despair", "vi", "灰心丧气", "破坏", "侦察(用)的 n", "决心"));
        list.add(new Word(104, "desk", "n", "书桌", "灰心丧气", "破坏", "侦察(用)的 n"));
        list.add(new Word(105, "desire", "n", "愿望", "书桌", "灰心丧气", "破坏"));
        list.add(new Word(106, "designer", "n", "设计者", "愿望", "书桌", "灰心丧气"));
        list.add(new Word(107, "design", "n", "设计", "设计者", "愿望", "书桌"));
        list.add(new Word(108, "deserted", "adj", "(街道等)无人通行的", "设计", "设计者", "愿望"));
        list.add(new Word(109, "desert", "n", "/a", "(街道等)无人通行的", "设计", "设计者"));
        list.add(new Word(110, "description", "n", "描写", "/a", "(街道等)无人通行的", "设计"));
        list.add(new Word(111, "describe", "vt", "描绘", "描写", "/a", "(街道等)无人通行的"));
        list.add(new Word(112, "depth", "n", "深(度)", "描绘", "描写", "/a"));
        list.add(new Word(113, "depend", "v", "(on)依靠", "深(度)", "描绘", "描写"));
        list.add(new Word(114, "department", "n", "(行政)部", "(on)依靠", "深(度)", "描绘"));
        list.add(new Word(115, "demand", "vt", "要求", "(行政)部", "(on)依靠", "深(度)"));
        list.add(new Word(116, "delivery", "n", "投递", "要求", "(行政)部", "(on)依靠"));
        list.add(new Word(117, "deliver", "vt", "投递交", "投递", "要求", "(行政)部"));
        list.add(new Word(118, "delighted", "*a", "高兴的", "投递交", "投递", "要求"));
        list.add(new Word(119, "delight", "n", "高兴", "高兴的", "投递交", "投递"));
        list.add(new Word(120, "delicious", "a", "美味可口的", "高兴", "高兴的", "投递交"));
        list.add(new Word(121, "delay", "n", "耽搁", "美味可口的", "高兴", "高兴的"));
        list.add(new Word(122, "degree", "n", "(角或温度的)度数", "耽搁", "美味可口的", "高兴"));
        list.add(new Word(123, "definite", "a", "明确的", "(角或温度的)度数", "耽搁", "美味可口的"));
        list.add(new Word(124, "defend", "vt", "保卫", "明确的", "(角或温度的)度数", "耽搁"));
        list.add(new Word(125, "defence", "n", "防御", "保卫", "明确的", "(角或温度的)度数"));
        list.add(new Word(126, "defeat", "vt", "战胜", "防御", "保卫", "明确的"));
        list.add(new Word(127, "deer", "n", "［单复同形］鹿 ", "战胜", "防御", "保卫"));
        list.add(new Word(128, "deeply", "ad", "深深地", "［单复同形］鹿 ", "战胜", "防御"));
        list.add(new Word(129, "deep", "a", "深的", "深深地", "［单复同形］鹿 ", "战胜"));
        list.add(new Word(130, "deed", "n", "行为", "深的", "深深地", "［单复同形］鹿 "));
        list.add(new Word(131, "declare", "v", "宣告", "行为", "深的", "深深地"));
        list.add(new Word(132, "decision", "n", "决定", "宣告", "行为", "深的"));
        list.add(new Word(133, "decide", "vt", "决定", "决定", "宣告", "行为"));
        list.add(new Word(134, "debt", "n", "债(务)", "决定", "决定", "宣告"));
        list.add(new Word(135, "death", "n", "死", "债(务)", "决定", "决定"));
        list.add(new Word(136, "dear", "a", "昂贵的", "死", "债(务)", "决定"));
        list.add(new Word(137, "deal", "v", "处理", "昂贵的", "死", "债(务)"));
        list.add(new Word(138, "deaf", "a", "聋的", "处理", "昂贵的", "死"));
        list.add(new Word(139, "dead", "a", "死的", "聋的", "处理", "昂贵的"));
        list.add(new Word(140, "daytime", "n", "白天", "死的", "聋的", "处理"));
        list.add(new Word(141, "daylight", "n", "白天", "白天", "死的", "聋的"));
        list.add(new Word(142, "day", "n", "天", "白天", "白天", "死的"));
        list.add(new Word(143, "dawn", "vi", "破晓", "天", "白天", "白天"));
        list.add(new Word(144, "date", "n", "日期", "破晓", "天", "白天"));
        list.add(new Word(145, "darkness", "n", "黑暗", "日期", "破晓", "天"));
        list.add(new Word(146, "dark", "a", "黑暗的", "黑暗", "日期", "破晓"));
        list.add(new Word(147, "dare", "vt", "敢", "黑暗的", "黑暗", "日期"));
        list.add(new Word(148, "dangerous", "a", "危险的", "敢", "黑暗的", "黑暗"));
        list.add(new Word(149, "danger", "n", "危险", "危险的", "敢", "黑暗的"));
        list.add(new Word(150, "dance", "n", "舞(蹈)", "危险", "危险的", "敢"));
        list.add(new Word(151, "damp", "a", "潮湿的 n", "舞(蹈)", "危险", "危险的"));
        list.add(new Word(152, "damage", "n", "损害", "潮湿的 n", "舞(蹈)", "危险"));
        list.add(new Word(153, "dam", "n", "水坝", "损害", "潮湿的 n", "舞(蹈)"));
        list.add(new Word(154, "daily", "a", "每日的", "水坝", "损害", "潮湿的 n"));
        list.add(new Word(155, "dad", "n", "(口语)爸爸", "每日的", "水坝", "损害"));
        list.add(new Word(156, "cycle", "n", "周期", "(口语)爸爸", "每日的", "水坝"));
        list.add(new Word(157, "cut", "n", "/v", "周期", "(口语)爸爸", "每日的"));
        list.add(new Word(158, "customer", "n", "顾客", "/v", "周期", "(口语)爸爸"));
        list.add(new Word(159, "custom", "n", "习惯", "顾客", "/v", "周期"));
        list.add(new Word(160, "cushion", "n", "垫子 v", "习惯", "顾客", "/v"));
        list.add(new Word(161, "curtain", "n", "窗帘", "垫子 v", "习惯", "顾客"));
        list.add(new Word(162, "curiously", "ad", "有求知欲地", "窗帘", "垫子 v", "习惯"));
        list.add(new Word(163, "curious", "a", "好奇的", "有求知欲地", "窗帘", "垫子 v"));
        list.add(new Word(164, "cure", "vt", "治愈", "好奇的", "有求知欲地", "窗帘"));
        list.add(new Word(165, "cupboard", "n", "碗柜", "治愈", "好奇的", "有求知欲地"));
        list.add(new Word(166, "cup", "n", "杯子", "碗柜", "治愈", "好奇的"));
        list.add(new Word(167, "cubic", "a", "立方形的", "杯子", "碗柜", "治愈"));
        list.add(new Word(168, "cry", "n", "&v", "立方形的", "杯子", "碗柜"));
        list.add(new Word(169, "cruel", "a", "残酷的", "&v", "立方形的", "杯子"));
        list.add(new Word(170, "crowd", "n", "群", "残酷的", "&v", "立方形的"));
        list.add(new Word(171, "crossing", "n", "横渡(大海)", "群", "残酷的", "&v"));
        list.add(new Word(172, "cross", "n", "十字(架)", "横渡(大海)", "群", "残酷的"));
        list.add(new Word(173, "crop", "n", "庄稼", "十字(架)", "横渡(大海)", "群"));
        list.add(new Word(174, "crisp", "a", "脆的", "庄稼", "十字(架)", "横渡(大海)"));
        list.add(new Word(175, "crew", "n", "(船、飞机等的)全体人员", "脆的", "庄稼", "十字(架)"));
        list.add(new Word(176, "creative", "a", "创造(性)的", "(船、飞机等的)全体人员", "脆的", "庄稼"));
        list.add(new Word(177, "creat", "vt", "创造 ", "创造(性)的", "(船、飞机等的)全体人员", "脆的"));
        list.add(new Word(178, "cream", "n", "奶油", "创造 ", "创造(性)的", "(船、飞机等的)全体人员"));
        list.add(new Word(179, "crazy", "a", "发疯的,荒唐的,古怪的;(about)狂热爱好的 ", "奶油", "创造 ", "创造(性)的"));
        list.add(new Word(180, "co-worker", "n", "共同工作者", "发疯的,荒唐的,古怪的;(about)狂热爱好的 ", "奶油", "创造 "));
        list.add(new Word(181, "cow", "n", "母牛", "共同工作者", "发疯的,荒唐的,古怪的;(about)狂热爱好的 ", "奶油"));
        list.add(new Word(182, "cover", "vt", "覆盖", "母牛", "共同工作者", "发疯的,荒唐的,古怪的;(about)狂热爱好的 "));
        list.add(new Word(183, "cousin", "n", "堂(表)兄弟", "覆盖", "母牛", "共同工作者"));
        list.add(new Word(184, "courtyard", "n", "院子", "堂(表)兄弟", "覆盖", "母牛"));
        list.add(new Word(185, "court", "n", "法院,法庭;庭院v", "院子", "堂(表)兄弟", "覆盖"));
        list.add(new Word(186, "course", "n", "课程", "法院,法庭;庭院v", "院子", "堂(表)兄弟"));
        list.add(new Word(187, "courage", "n", "勇气", "课程", "法院,法庭;庭院v", "院子"));
        list.add(new Word(188, "couple", "n", "对", "勇气", "课程", "法院,法庭;庭院v"));
        list.add(new Word(189, "countryside", "n", "农村", "对", "勇气", "课程"));
        list.add(new Word(190, "country", "n", "国家", "农村", "对", "勇气"));
        list.add(new Word(191, "countless", "a", "无数的", "国家", "农村", "对"));
        list.add(new Word(192, "counter", "n", "柜台", "无数的", "国家", "农村"));
        list.add(new Word(193, "count", "v", "计算", "柜台", "无数的", "国家"));
        list.add(new Word(194, "could", "v", "aux", "计算", "柜台", "无数的"));
        list.add(new Word(195, "cough", "vi", "咳", "aux", "计算", "柜台"));
        list.add(new Word(196, "cotton", "n", "棉花", "咳", "aux", "计算"));
        list.add(new Word(197, "cottage", "n", "农舍", "棉花", "咳", "aux"));
        list.add(new Word(198, "cost", "v", "值", "农舍", "棉花", "咳"));
        list.add(new Word(199, "correctly", "adv", "正确地", "值", "农舍", "棉花"));
        list.add(new Word(200, "correction", "n", "改正", "正确地", "值", "农舍"));
        list.add(new Word(201, "correct", "a", "正确的", "改正", "正确地", "值"));
        list.add(new Word(202, "corn", "n", "谷物", "正确的", "改正", "正确地"));
        list.add(new Word(203, "cordless", "adj", "无线的 ", "谷物", "正确的", "改正"));
        list.add(new Word(204, "coral", "n", "珊瑚a", "无线的 ", "谷物", "正确的"));
        list.add(new Word(205, "copybook", "n", "习字簿", "珊瑚a", "无线的 ", "谷物"));
        list.add(new Word(206, "copy", "n", "抄本", "习字簿", "珊瑚a", "无线的 "));
        list.add(new Word(207, "cool", "a", "凉的", "抄本", "习字簿", "珊瑚a"));
        list.add(new Word(208, "cookie", "n", "a sweet cookie曲奇饼 ", "凉的", "抄本", "习字簿"));
        list.add(new Word(209, "cooker", "n", "炊事用具(尤指炉、锅等) ", "a sweet cookie曲奇饼 ", "凉的", "抄本"));
        list.add(new Word(210, "cookbook", "*n", "食谱", "炊事用具(尤指炉、锅等) ", "a sweet cookie曲奇饼 ", "凉的"));
        list.add(new Word(211, "cook", "n", "厨师 v", "食谱", "炊事用具(尤指炉、锅等) ", "a sweet cookie曲奇饼 "));
        list.add(new Word(212, "conversation", "n", "(友好、随便的)谈话", "厨师 v", "食谱", "炊事用具(尤指炉、锅等) "));
        list.add(new Word(213, "convenient", "a", "(to)方便的", "(友好、随便的)谈话", "厨师 v", "食谱"));
        list.add(new Word(214, "control", "n", "对照物在对照实验中被用作对照标准的物体 ", "(to)方便的", "(友好、随便的)谈话", "厨师 v"));
        list.add(new Word(215, "contribution", "n", "贡献", "对照物在对照实验中被用作对照标准的物体 ", "(to)方便的", "(友好、随便的)谈话"));
        list.add(new Word(216, "contrary", "a", "(to)相反的", "贡献", "对照物在对照实验中被用作对照标准的物体 ", "(to)方便的"));
        list.add(new Word(217, "continue", "v", "(使)继续", "(to)相反的", "贡献", "对照物在对照实验中被用作对照标准的物体 "));
        list.add(new Word(218, "continent", "n", "大陆", "(使)继续", "(to)相反的", "贡献"));
        list.add(new Word(219, "content", "n", "目录", "大陆", "(使)继续", "(to)相反的"));
        list.add(new Word(220, "container", "n", "容器", "目录", "大陆", "(使)继续"));
        list.add(new Word(221, "contain", "v", "包含", "容器", "目录", "大陆"));
        list.add(new Word(222, "construction", "n", "建造", "包含", "容器", "目录"));
        list.add(new Word(223, "constantly", "ad", "经常地", "建造", "包含", "容器"));
        list.add(new Word(224, "constant", "a", "经常的", "经常地", "建造", "包含"));
        list.add(new Word(225, "consider", "v", "考虑", "经常的", "经常地", "建造"));
        list.add(new Word(226, "connection", "n", "联系", "考虑", "经常的", "经常地"));
        list.add(new Word(227, "connected", "adj", "连接的", "联系", "考虑", "经常的"));
        list.add(new Word(228, "connect", "vt", "连接", "连接的", "联系", "考虑"));
        list.add(new Word(229, "conjecture", "n", "/v", "连接", "连接的", "联系"));
        list.add(new Word(230, "congratulation", "n", "祝贺", "/v", "连接", "连接的"));
        list.add(new Word(231, "congratulate", "vt", "(on", "祝贺", "/v", "连接"));
        list.add(new Word(232, "confuse", "vt", "使困惑", "(on", "祝贺", "/v"));
        list.add(new Word(233, "conference", "n", "(正式)会议", "使困惑", "(on", "祝贺"));
        list.add(new Word(234, "conductor", "n", "导体", "(正式)会议", "使困惑", "(on"));
        list.add(new Word(235, "conduct", "n", "表现", "导体", "(正式)会议", "使困惑"));
        list.add(new Word(236, "condition", "n", "条件", "表现", "导体", "(正式)会议"));
        list.add(new Word(237, "conclusion", "n", "结论", "条件", "表现", "导体"));
        list.add(new Word(238, "conclude", "", " ", "结论", "条件", "表现"));
        list.add(new Word(239, "concert", "n", "音乐会", " ", "结论", "条件"));
        list.add(new Word(240, "conceited", "a", "骄傲自满的", "音乐会", " ", "结论"));
        list.add(new Word(241, "comradeship", "n", "同志关系", "骄傲自满的", "音乐会", " "));
        list.add(new Word(242, "comrade", "n", "伙伴", "同志关系", "骄傲自满的", "音乐会"));
        list.add(new Word(243, "computer", "n", "计算机", "伙伴", "同志关系", "骄傲自满的"));
        list.add(new Word(244, "compromise", "n", "妥协", "计算机", "伙伴", "同志关系"));
        list.add(new Word(245, "compressed", "a", "压缩的", "妥协", "计算机", "伙伴"));
        list.add(new Word(246, "composition", "n", "构成", "压缩的", "妥协", "计算机"));
        list.add(new Word(247, "complex", "a", "复合的", "构成", "压缩的", "妥协"));
        list.add(new Word(248, "completely", "ad", "完全地", "复合的", "构成", "压缩的"));
        list.add(new Word(249, "complete", "a", "完整的", "完全地", "复合的", "构成"));
        list.add(new Word(250, "competitor", "n", "竞争对手", "完整的", "完全地", "复合的"));
        list.add(new Word(251, "competition", "n", "竞争", "竞争对手", "完整的", "完全地"));
        list.add(new Word(252, "compete", "vi", "比赛", "竞争", "竞争对手", "完整的"));
        list.add(new Word(253, "compare", "vt", "(to", "比赛", "竞争", "竞争对手"));
        list.add(new Word(254, "company", "n", "公司", "(to", "比赛", "竞争"));
        list.add(new Word(255, "companion", "n", "同伴", "公司", "(to", "比赛"));
        list.add(new Word(256, "communist", "a", "共产主义(党)的 n", "同伴", "公司", "(to"));
        list.add(new Word(257, "communism", "n", "共产主义", "共产主义(党)的 n", "同伴", "公司"));
        list.add(new Word(258, "communicate", "vt", "交际", "共产主义", "共产主义(党)的 n", "同伴"));
        list.add(new Word(259, "common", "a", "平常的", "交际", "共产主义", "共产主义(党)的 n"));
        list.add(new Word(260, "comment", "vi", "发表意见", "平常的", "交际", "共产主义"));
        list.add(new Word(261, "command", "n", "/v", "发表意见", "平常的", "交际"));
        list.add(new Word(262, "comfortable", "a", "舒适的", "/v", "发表意见", "平常的"));
        list.add(new Word(263, "comfort", "n", "舒适", "舒适的", "/v", "发表意见"));
        list.add(new Word(264, "comer", "n", "有(成功)希望的人 ", "舒适", "舒适的", "/v"));
        list.add(new Word(265, "comedy", "n", "喜剧", "有(成功)希望的人 ", "舒适", "舒适的"));
        list.add(new Word(266, "come", "v", "来", "喜剧", "有(成功)希望的人 ", "舒适"));
        list.add(new Word(267, "combine", "v", "联合", "来", "喜剧", "有(成功)希望的人 "));
        list.add(new Word(268, "comb", "vt", "用梳子梳(comb也可作名词,表示“梳子”) ", "联合", "来", "喜剧"));
        list.add(new Word(269, "coloured", "a", "有色的 n", "用梳子梳(comb也可作名词,表示“梳子”) ", "联合", "来"));
        list.add(new Word(270, "colorful", "a", "富有色彩的", "有色的 n", "用梳子梳(comb也可作名词,表示“梳子”) ", "联合"));
        list.add(new Word(271, "color", "n", "颜色", "富有色彩的", "有色的 n", "用梳子梳(comb也可作名词,表示“梳子”) "));
        list.add(new Word(272, "college", "n", "(综合大学中的)学院", "颜色", "富有色彩的", "有色的 n"));
        list.add(new Word(273, "collection", "n", "收取", "(综合大学中的)学院", "颜色", "富有色彩的"));
        list.add(new Word(274, "collect", "v", "收集", "收取", "(综合大学中的)学院", "颜色"));
        list.add(new Word(275, "collar", "n", "衣领", "收集", "收取", "(综合大学中的)学院"));
        list.add(new Word(276, "cold-blooded", "a", "(指人或行为)无情的", "衣领", "收集", "收取"));
        list.add(new Word(277, "cold", "a", "冷的", "(指人或行为)无情的", "衣领", "收集"));
        list.add(new Word(278, "coin", "n", "硬币", "冷的", "(指人或行为)无情的", "衣领"));
        list.add(new Word(279, "coffee", "n", "咖啡", "硬币", "冷的", "(指人或行为)无情的"));
        list.add(new Word(280, "coda", "n", "终结句,乐章结尾部,完结部 ", "咖啡", "硬币", "冷的"));
        list.add(new Word(281, "cocoa", "cmeravt", "可可", "终结句,乐章结尾部,完结部 ", "咖啡", "硬币"));
        list.add(new Word(282, "coat", "n", "上衣", "可可", "终结句,乐章结尾部,完结部 ", "咖啡"));
        list.add(new Word(283, "coastline", "*n", "海岸线 ", "上衣", "可可", "终结句,乐章结尾部,完结部 "));
        list.add(new Word(284, "coastal", "a", "海岸的", "海岸线 ", "上衣", "可可"));
        list.add(new Word(285, "coast", "v", "投掷", "海岸的", "海岸线 ", "上衣"));
        list.add(new Word(286, "coal", "n", "煤", "投掷", "海岸的", "海岸线 "));
        list.add(new Word(287, "club", "n", "俱乐部", "煤", "投掷", "海岸的"));
        list.add(new Word(288, "cloudy", "a", "多云的", "俱乐部", "煤", "投掷"));
        list.add(new Word(289, "cloud", "n", "云", "多云的", "俱乐部", "煤"));
        list.add(new Word(290, "clothing", "n", "衣服(集合名词", "云", "多云的", "俱乐部"));
        list.add(new Word(291, "clothes", "n", "衣服(虽为复数", "衣服(集合名词", "云", "多云的"));
        list.add(new Word(292, "cloth", "n", "布", "衣服(虽为复数", "衣服(集合名词", "云"));
        list.add(new Word(293, "closed", "a", "关闭的", "布", "衣服(虽为复数", "衣服(集合名词"));
        list.add(new Word(294, "close", "v", "/n", "关闭的", "布", "衣服(虽为复数"));
        list.add(new Word(295, "clock", "n", "钟 vt", "/n", "关闭的", "布"));
        list.add(new Word(296, "clinic", "n", "诊所", "钟 vt", "/n", "关闭的"));
        list.add(new Word(297, "climb", "v", "攀登", "诊所", "钟 vt", "/n"));
        list.add(new Word(298, "clever", "a", "聪明的", "攀登", "诊所", "钟 vt"));
        list.add(new Word(299, "clerk", "n", "职员", "聪明的", "攀登", "诊所"));
        list.add(new Word(300, "clear", "a", "/ad", "职员", "聪明的", "攀登"));
        list.add(new Word(301, "clean", "a", "清洁的", "/ad", "职员", "聪明的"));
        list.add(new Word(302, "Clause", "n", "(正式文件或法律文件的)条款", "清洁的", "/ad", "职员"));
        list.add(new Word(303, "class", "n", "班级", "(正式文件或法律文件的)条款", "清洁的", "/ad"));
        list.add(new Word(304, "clap", "v", "拍手", "班级", "(正式文件或法律文件的)条款", "清洁的"));
        list.add(new Word(305, "civil", "a", "公民(个人)的", "拍手", "班级", "(正式文件或法律文件的)条款"));
        list.add(new Word(306, "citizenship", "n", "市民权", "公民(个人)的", "拍手", "班级"));
        list.add(new Word(307, "citizen", "n", "公民", "市民权", "公民(个人)的", "拍手"));
        list.add(new Word(308, "circle", "n", "圆(周)", "公民", "市民权", "公民(个人)的"));
        list.add(new Word(309, "cinema", "n", "电影院", "圆(周)", "公民", "市民权"));
        list.add(new Word(310, "cigarette", "n", "香烟", "电影院", "圆(周)", "公民"));
        list.add(new Word(311, "cigar", "n", "雪茄烟", "香烟", "电影院", "圆(周)"));
        list.add(new Word(312, "church", "n", "教堂", "雪茄烟", "香烟", "电影院"));
        list.add(new Word(313, "chore", "n", "杂务", "教堂", "雪茄烟", "香烟"));
        list.add(new Word(314, "chopstick", "n", "筷子(常用复数) ", "杂务", "教堂", "雪茄烟"));
        list.add(new Word(315, "choose", "vt", "挑选", "筷子(常用复数) ", "杂务", "教堂"));
        list.add(new Word(316, "choke", "v", "窒息", "挑选", "筷子(常用复数) ", "杂务"));
        list.add(new Word(317, "choice", "n", "选择(权)", "窒息", "挑选", "筷子(常用复数) "));
        list.add(new Word(318, "chocolate", "n", "巧克力", "选择(权)", "窒息", "挑选"));
        list.add(new Word(319, "chip", "n", "片屑", "巧克力", "选择(权)", "窒息"));
        list.add(new Word(320, "Chinese", "a", "中国的", "片屑", "巧克力", "选择(权)"));
        list.add(new Word(321, "China", "n", "瓷器(制品)", "中国的", "片屑", "巧克力"));
        list.add(new Word(322, "chimney", "n", "烟囱", "瓷器(制品)", "中国的", "片屑"));
        list.add(new Word(323, "chime", "n", "(乐器、钟等奏出的)谐和的乐声 ", "烟囱", "瓷器(制品)", "中国的"));
        list.add(new Word(324, "childhood", "n", "童年", "(乐器、钟等奏出的)谐和的乐声 ", "烟囱", "瓷器(制品)"));
        list.add(new Word(325, "child", "n", "( [pl", "童年", "(乐器、钟等奏出的)谐和的乐声 ", "烟囱"));
        list.add(new Word(326, "child", "n", "( [pl", "( [pl", "童年", "(乐器、钟等奏出的)谐和的乐声 "));
        list.add(new Word(327, "chief", "a", "主要的", "( [pl", "( [pl", "童年"));
        list.add(new Word(328, "chicken", "n", "鸡肉", "主要的", "( [pl", "( [pl"));
        list.add(new Word(329, "chew", "vt", "咀嚼", "鸡肉", "主要的", "( [pl"));
        list.add(new Word(330, "chest", "n", "胸部", "咀嚼", "鸡肉", "主要的"));
        list.add(new Word(331, "cheque", "n", "支票", "胸部", "咀嚼", "鸡肉"));
        list.add(new Word(332, "chemistry", "n", "化学 ", "支票", "胸部", "咀嚼"));
        list.add(new Word(333, "chemist", "n", "化学家", "化学 ", "支票", "胸部"));
        list.add(new Word(334, "chemical", "a", "化学的", "化学家", "化学 ", "支票"));
        list.add(new Word(335, "cheerful", "a", "欢乐的", "化学的", "化学家", "化学 "));
        list.add(new Word(336, "cheer", "vt", "使高兴", "欢乐的", "化学的", "化学家"));
        list.add(new Word(337, "cheek", "n", "面颊", "使高兴", "欢乐的", "化学的"));
        list.add(new Word(338, "check", "vt", "/n", "面颊", "使高兴", "欢乐的"));
        list.add(new Word(339, "cheat", "vt", "欺骗", "/n", "面颊", "使高兴"));
        list.add(new Word(340, "cheaply", "ad", "廉价地", "欺骗", "/n", "面颊"));
        list.add(new Word(341, "cheap", "a", "便宜的", "廉价地", "欺骗", "/n"));
        list.add(new Word(342, "chat", "n", "／vi", "便宜的", "廉价地", "欺骗"));
        list.add(new Word(343, "chart", "n", "图表", "／vi", "便宜的", "廉价地"));
        list.add(new Word(344, "charge", "n", "费用", "图表", "／vi", "便宜的"));
        list.add(new Word(345, "character", "n", "个性", "费用", "图表", "／vi"));
        list.add(new Word(346, "chapter", "n", "a mai division of a book 章", "个性", "费用", "图表"));
        list.add(new Word(347, "channel", "n", "频道", "a mai division of a book 章", "个性", "费用"));
        list.add(new Word(348, "change", "n", "变化", "频道", "a mai division of a book 章", "个性"));
        list.add(new Word(349, "chance", "vi", "碰巧", "变化", "频道", "a mai division of a book 章"));
        list.add(new Word(350, "chalk", "vt", "用粉笔写或画 n", "碰巧", "变化", "频道"));
        list.add(new Word(351, "chairman", "n", "主席", "用粉笔写或画 n", "碰巧", "变化"));
        list.add(new Word(352, "chair", "n", "椅子", "主席", "用粉笔写或画 n", "碰巧"));
        list.add(new Word(353, "chain", "n", "链", "椅子", "主席", "用粉笔写或画 n"));
        list.add(new Word(354, "certainly", "ad", "1", "链", "椅子", "主席"));
        list.add(new Word(355, "certain", "a", "确实的", "1", "链", "椅子"));
        list.add(new Word(356, "century", "n", "世纪", "确实的", "1", "链"));
        list.add(new Word(357, "centre", "n", "中心", "世纪", "确实的", "1"));
        list.add(new Word(358, "central", "a", "中心的", "中心", "世纪", "确实的"));
        list.add(new Word(359, "centimetre", "*n", "公分", "中心的", "中心", "世纪"));
        list.add(new Word(360, "centigrade", "n", "/a", "公分", "中心的", "中心"));
        list.add(new Word(361, "cent", "n", "分", "/a", "公分", "中心的"));
        list.add(new Word(362, "celebration", "n", "庆祝会", "分", "/a", "公分"));
        list.add(new Word(363, "celebrate", "vt", "庆祝", "庆祝会", "分", "/a"));
        list.add(new Word(364, "ceiling", "n", "天花板", "庆祝", "庆祝会", "分"));
        list.add(new Word(365, "cave", "n", "山洞", "天花板", "庆祝", "庆祝会"));
        list.add(new Word(366, "cause", "n", "原因", "山洞", "天花板", "庆祝"));
        list.add(new Word(367, "cattle", "n", "(pl", "原因", "山洞", "天花板"));
        list.add(new Word(368, "catch", "vt", "捕捉", "(pl", "原因", "山洞"));
        list.add(new Word(369, "castor", "*n", "蓖麻 ", "捕捉", "(pl", "原因"));
        list.add(new Word(370, "castle", "n", "城堡", "蓖麻 ", "捕捉", "(pl"));
        list.add(new Word(371, "cast", "v", "投掷", "城堡", "蓖麻 ", "捕捉"));
        list.add(new Word(372, "cash", "vt", "兑换成现钱", "投掷", "城堡", "蓖麻 "));
        list.add(new Word(373, "case", "n", "事实", "兑换成现钱", "投掷", "城堡"));
        list.add(new Word(374, "carve", "vt", "切", "事实", "兑换成现钱", "投掷"));
        list.add(new Word(375, "cartoon", "n", "卡通片", "切", "事实", "兑换成现钱"));
        list.add(new Word(376, "cart", "n", "二轮马车", "卡通片", "切", "事实"));
        list.add(new Word(377, "carry", "vt", "运", "二轮马车", "卡通片", "切"));
        list.add(new Word(378, "carrot", "n", "红萝卜 ", "运", "二轮马车", "卡通片"));
        list.add(new Word(379, "carriage", "n", "马车", "红萝卜 ", "运", "二轮马车"));
        list.add(new Word(380, "carpet", "n", "地毯", "马车", "红萝卜 ", "运"));
        list.add(new Word(381, "carol", "n", "欢乐或赞美之歌", "地毯", "马车", "红萝卜 "));
        list.add(new Word(382, "carelessness", "n", "粗心", "欢乐或赞美之歌", "地毯", "马车"));
        list.add(new Word(383, "careless", "n", "粗心的", "粗心", "欢乐或赞美之歌", "地毯"));
        list.add(new Word(384, "carefully", "adv", "仔细地", "粗心的", "粗心", "欢乐或赞美之歌"));
        list.add(new Word(385, "careful", "a", "当心的", "仔细地", "粗心的", "粗心"));
        list.add(new Word(386, "care", "n", " 小心", "当心的", "仔细地", "粗心的"));
        list.add(new Word(387, "cardigan", "n", "卡迪根式开襟毛线衣 ", " 小心", "当心的", "仔细地"));
        list.add(new Word(388, "card", "n", "卡", "卡迪根式开襟毛线衣 ", " 小心", "当心的"));
        list.add(new Word(389, "car", "n", "汽车", "卡", "卡迪根式开襟毛线衣 ", " 小心"));
        list.add(new Word(390, "captain", "n", "首领", "汽车", "卡", "卡迪根式开襟毛线衣 "));
        list.add(new Word(391, "capital", "n", "首都", "首领", "汽车", "卡"));
        list.add(new Word(392, "cap", "n", "便帽", "首都", "首领", "汽车"));
        list.add(new Word(393, "can't", "v", "can not 的缩写 ", "便帽", "首都", "首领"));
        list.add(new Word(394, "candy", "n", "糖果", "can not 的缩写 ", "便帽", "首都"));
        list.add(new Word(395, "candle", "n", "蜡烛", "糖果", "can not 的缩写 ", "便帽"));
        list.add(new Word(396, "cancer", "n", "癌(通常为不可数名词) ", "蜡烛", "糖果", "can not 的缩写 "));
        list.add(new Word(397, "canal", "n", "运河", "癌(通常为不可数名词) ", "蜡烛", "糖果"));
        list.add(new Word(398, "Canadian", "a", "加拿大的", "运河", "癌(通常为不可数名词) ", "蜡烛"));
        list.add(new Word(399, "Canada", "n", "加拿大[北美洲] ", "加拿大的", "运河", "癌(通常为不可数名词) "));
        list.add(new Word(400, "can", "aux", "v", "加拿大[北美洲] ", "加拿大的", "运河"));
        list.add(new Word(401, "camp", "n", "野营", "v", "加拿大[北美洲] ", "加拿大的"));
        list.add(new Word(402, "camera", "n", "照相机", "野营", "v", "加拿大[北美洲] "));
        list.add(new Word(403, "calorie", "n", "卡路里(食物所产生的热量或能量单位) ", "照相机", "野营", "v"));
        list.add(new Word(404, "calm", "a", "(天气等)静的", "卡路里(食物所产生的热量或能量单位) ", "照相机", "野营"));
        list.add(new Word(405, "call", "vt", "叫", "(天气等)静的", "卡路里(食物所产生的热量或能量单位) ", "照相机"));
        list.add(new Word(406, "cake", "n", "饼", "叫", "(天气等)静的", "卡路里(食物所产生的热量或能量单位) "));
        list.add(new Word(407, "cage", "n", "笼子", "饼", "叫", "(天气等)静的"));
        list.add(new Word(408, "cafe", "n", "餐馆", "笼子", "饼", "叫"));
        list.add(new Word(409, "cabbage", "n", "洋白菜", "餐馆", "笼子", "饼"));
        list.add(new Word(410, "bye-bye", "interj", "再会", "洋白菜", "餐馆", "笼子"));
        list.add(new Word(411, "by", "prep", "被", "再会", "洋白菜", "餐馆"));
        list.add(new Word(412, "buy", "vt", "买", "被", "再会", "洋白菜"));
        list.add(new Word(413, "button", "n", "扣子", "买", "被", "再会"));
        list.add(new Word(414, "butter", "n", "黄油", "扣子", "买", "被"));
        list.add(new Word(415, "butcher", "n", "屠夫", "黄油", "扣子", "买"));
        list.add(new Word(416, "but", "conj", "但是 prep", "屠夫", "黄油", "扣子"));
        list.add(new Word(417, "busy", "a", "忙", "但是 prep", "屠夫", "黄油"));
        list.add(new Word(418, "business", "n", "生意(不可数)", "忙", "但是 prep", "屠夫"));
        list.add(new Word(419, "bush", "n", "灌木", "生意(不可数)", "忙", "但是 prep"));
        list.add(new Word(420, "bus", "n", "公共汽车", "灌木", "生意(不可数)", "忙"));
        list.add(new Word(421, "bury", "vt", "埋葬", "公共汽车", "灌木", "生意(不可数)"));
        list.add(new Word(422, "burst", "vi", "/n", "埋葬", "公共汽车", "灌木"));
        list.add(new Word(423, "burn", "v", "燃烧", "/n", "埋葬", "公共汽车"));
        list.add(new Word(424, "burial", "n", "安葬", "燃烧", "/n", "埋葬"));
        list.add(new Word(425, "building", "n", "建筑(物)", "安葬", "燃烧", "/n"));
        list.add(new Word(426, "builder", "n", "建筑工人", "建筑(物)", "安葬", "燃烧"));
        list.add(new Word(427, "build", "vt", "建造", "建筑工人", "建筑(物)", "安葬"));
        list.add(new Word(428, "bucket", "n", "水桶", "建造", "建筑工人", "建筑(物)"));
        list.add(new Word(429, "brush", "n", "刷子;轻碰;小冲突vt", "水桶", "建造", "建筑工人"));
        list.add(new Word(430, "brown", "a", "&n", "刷子;轻碰;小冲突vt", "水桶", "建造"));
        list.add(new Word(431, "brotherly", "a", "兄弟般的 ", "&n", "刷子;轻碰;小冲突vt", "水桶"));
        list.add(new Word(432, "brotherhood", "n", "手足情谊", "兄弟般的 ", "&n", "刷子;轻碰;小冲突vt"));
        list.add(new Word(433, "brother", "n", "兄弟", "手足情谊", "兄弟般的 ", "&n"));
        list.add(new Word(434, "broom", "n", "扫帚 vt", "兄弟", "手足情谊", "兄弟般的 "));
        list.add(new Word(435, "broken", "a", "破的", "扫帚 vt", "兄弟", "手足情谊"));
        list.add(new Word(436, "broadcaster", "n", "播音员 ", "破的", "扫帚 vt", "兄弟"));
        list.add(new Word(437, "broadcast", "n", "广播", "播音员 ", "破的", "扫帚 vt"));
        list.add(new Word(438, "broad", "a", "宽的", "广播", "播音员 ", "破的"));
        list.add(new Word(439, "British", "a", "(大)不列颠(人)的", "宽的", "广播", "播音员 "));
        list.add(new Word(440, "Britain", "n", "英国", "(大)不列颠(人)的", "宽的", "广播"));
        list.add(new Word(441, "bring", "v", "拿来", "英国", "(大)不列颠(人)的", "宽的"));
        list.add(new Word(442, "brightly", "adv", "明亮地", "拿来", "英国", "(大)不列颠(人)的"));
        list.add(new Word(443, "bright", "a", "明亮的", "明亮地", "拿来", "英国"));
        list.add(new Word(444, "brief", "a", "简要的", "明亮的", "明亮地", "拿来"));
        list.add(new Word(445, "bridge", "n", "桥", "简要的", "明亮的", "明亮地"));
        list.add(new Word(446, "brick", "n", "砖块", "桥", "简要的", "明亮的"));
        list.add(new Word(447, "breathe", "n", "呼吸", "砖块", "桥", "简要的"));
        list.add(new Word(448, "breath", "n", "气息", "呼吸", "砖块", "桥"));
        list.add(new Word(449, "breast", "n", "胸脯", "气息", "呼吸", "砖块"));
        list.add(new Word(450, "breakfast", "n", "早餐 v", "胸脯", "气息", "呼吸"));
        list.add(new Word(451, "break", "vt", "打破", "早餐 v", "胸脯", "气息"));
        list.add(new Word(452, "bread", "n", "面包", "打破", "早餐 v", "胸脯"));
        list.add(new Word(453, "brave", "a", "勇敢的 v", "面包", "打破", "早餐 v"));
        list.add(new Word(454, "branch", "n", "树枝", "勇敢的 v", "面包", "打破"));
        list.add(new Word(455, "brake", "n", "制动器", "树枝", "勇敢的 v", "面包"));
        list.add(new Word(456, "brain", "n", "脑", "制动器", "树枝", "勇敢的 v"));
        list.add(new Word(457, "boyhood", "n", "少年时代(期) ", "脑", "制动器", "树枝"));
        list.add(new Word(458, "boy", "n", "男孩子", "少年时代(期) ", "脑", "制动器"));
        list.add(new Word(459, "box", "n", "盒", "男孩子", "少年时代(期) ", "脑"));
        list.add(new Word(460, "bowl", "n", "碗", "盒", "男孩子", "少年时代(期) "));
        list.add(new Word(461, "bow", "n", "弓", "碗", "盒", "男孩子"));
        list.add(new Word(462, "bottom", "n", "底", "弓", "碗", "盒"));
        list.add(new Word(463, "bottle", "n", "瓶子", "底", "弓", "碗"));
        list.add(new Word(464, "both", "prep", "两者(都)", "瓶子", "底", "弓"));
        list.add(new Word(465, "botany", "*n", "植物", "两者(都)", "瓶子", "底"));
        list.add(new Word(466, "boss", "n", "老板", "植物", "两者(都)", "瓶子"));
        list.add(new Word(467, "borrow", "vt", "借", "老板", "植物", "两者(都)"));
        list.add(new Word(468, "born", "a", "出生的", "借", "老板", "植物"));
        list.add(new Word(469, "boring", "a", "令人厌倦的", "出生的", "借", "老板"));
        list.add(new Word(470, "bored", "a", "厌烦的", "令人厌倦的", "出生的", "借"));
        list.add(new Word(471, "border", "n", "边", "厌烦的", "令人厌倦的", "出生的"));
        list.add(new Word(472, "boot", "n", "靴", "边", "厌烦的", "令人厌倦的"));
        list.add(new Word(473, "bookstore", "n", "(=bookshop)书店 ", "靴", "边", "厌烦的"));


    }


    public static ArrayList<Word> getAllList(){
        if (list.size() == 0){
            setAllList();
        }
        return list;
    }


}
